apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-test
  template:
    metadata:
      labels:
        app: kubernetes-test
    spec:
      containers:
        - name: kubernetes-test
          image: kubernetes-test-image:latest
          imagePullPolicy: Never #ensures that only pre-approved, locally available images are used
          ports:
            - containerPort: 8080
