apiVersion: v1
kind: Service
metadata:
  name: kubernetes-test-service
spec:
  selector:
    app: kubernetes-test
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort